# Generated by Django 5.2.7 on 2025-12-14 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0006_create_offices"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="id_number",
            field=models.CharField(
                blank=True,
                max_length=9,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^\\d{1,9}$", "ID Number must contain only up to 9 digits."
                    )
                ],
            ),
        ),
    ]
