# Generated by Django 5.2.7 on 2025-11-08 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0002_tickethistory_ticket_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tickethistory",
            name="action",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="tickethistory",
            name="ticket",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="tickets.ticket",
            ),
        ),
        migrations.AlterField(
            model_name="tickethistory",
            name="ticket_title",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
