# Generated by Django 5.2.7 on 2025-11-14 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0007_notification"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="last_admin_update",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ticket",
            name="last_viewed_by_user",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
