# Generated by Django 5.2.7 on 2025-11-15 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_ticket_last_admin_update_ticket_last_viewed_by_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="tickethistory",
            name="new_status",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
