# Generated by Django 5.2.7 on 2025-12-14 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_tickethistory_new_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
